require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RepotsController do

  # This should return the minimal set of attributes required to create a valid
  # Repot. As you add validations to Repot, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RepotsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all repots as @repots" do
      repot = Repot.create! valid_attributes
      get :index, {}, valid_session
      assigns(:repots).should eq([repot])
    end
  end

  describe "GET show" do
    it "assigns the requested repot as @repot" do
      repot = Repot.create! valid_attributes
      get :show, {:id => repot.to_param}, valid_session
      assigns(:repot).should eq(repot)
    end
  end

  describe "GET new" do
    it "assigns a new repot as @repot" do
      get :new, {}, valid_session
      assigns(:repot).should be_a_new(Repot)
    end
  end

  describe "GET edit" do
    it "assigns the requested repot as @repot" do
      repot = Repot.create! valid_attributes
      get :edit, {:id => repot.to_param}, valid_session
      assigns(:repot).should eq(repot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Repot" do
        expect {
          post :create, {:repot => valid_attributes}, valid_session
        }.to change(Repot, :count).by(1)
      end

      it "assigns a newly created repot as @repot" do
        post :create, {:repot => valid_attributes}, valid_session
        assigns(:repot).should be_a(Repot)
        assigns(:repot).should be_persisted
      end

      it "redirects to the created repot" do
        post :create, {:repot => valid_attributes}, valid_session
        response.should redirect_to(Repot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved repot as @repot" do
        # Trigger the behavior that occurs when invalid params are submitted
        Repot.any_instance.stub(:save).and_return(false)
        post :create, {:repot => {}}, valid_session
        assigns(:repot).should be_a_new(Repot)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Repot.any_instance.stub(:save).and_return(false)
        post :create, {:repot => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested repot" do
        repot = Repot.create! valid_attributes
        # Assuming there are no other repots in the database, this
        # specifies that the Repot created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Repot.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => repot.to_param, :repot => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested repot as @repot" do
        repot = Repot.create! valid_attributes
        put :update, {:id => repot.to_param, :repot => valid_attributes}, valid_session
        assigns(:repot).should eq(repot)
      end

      it "redirects to the repot" do
        repot = Repot.create! valid_attributes
        put :update, {:id => repot.to_param, :repot => valid_attributes}, valid_session
        response.should redirect_to(repot)
      end
    end

    describe "with invalid params" do
      it "assigns the repot as @repot" do
        repot = Repot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Repot.any_instance.stub(:save).and_return(false)
        put :update, {:id => repot.to_param, :repot => {}}, valid_session
        assigns(:repot).should eq(repot)
      end

      it "re-renders the 'edit' template" do
        repot = Repot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Repot.any_instance.stub(:save).and_return(false)
        put :update, {:id => repot.to_param, :repot => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested repot" do
      repot = Repot.create! valid_attributes
      expect {
        delete :destroy, {:id => repot.to_param}, valid_session
      }.to change(Repot, :count).by(-1)
    end

    it "redirects to the repots list" do
      repot = Repot.create! valid_attributes
      delete :destroy, {:id => repot.to_param}, valid_session
      response.should redirect_to(repots_url)
    end
  end

end
